version: "3"

services:
  server:
    image: ghcr.io/andreasofthings/apcimage:latest
    container_name: apc
    user: 1000:1000
    restart: always
    env:
      - PORT: 8000
      - HOST: 0.0.0.0
      - SECRET_KEY: "Q1EdStnAXV8eKPdDdveDwIXP8DgeikBtNKCwMJ5E"
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000" # Same as above
